name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  archlinux:
    name: ArchLinux
    runs-on: ubuntu-latest
    container: docker.io/library/archlinux:latest
    steps:
    - name: dependencies
      run: pacman -Sy; pacman -S fishui qt5-svg extra-cmake-modules qt5-tools
    - name: Build
      run: mkdir build; cd build; cmake .. ; make -j$(nproc);

  debian:
    name: Debian
    runs-on: ubuntu-latest
    container: docker.io/library/debian:sid
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Update repository
      run: apt-get update -y
    - name: Install the basic dev packages
      run: apt-get install -y equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++
    - name: Install build dependencies
      run: mk-build-deps -i -t "apt-get --yes" -r
    - name: Build Package
      run: dpkg-buildpackage -b -uc -us -j$(nproc)

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Update repository
      run: sudo apt-get update -y
    - name: Install the basic dev packages
      run: sudo apt-get install -y equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++
    - name: Install build dependencies
      run: sudo mk-build-deps -i -t "apt-get --yes" -r
    - name: Build Package
      run: dpkg-buildpackage -b -uc -us -j$(nproc)
